# Trading Engine Test Configuration

[ws_pool]
max_connections_per_exchange = 2
heartbeat_interval_ms = 30000
reconnect_delay_ms = 1000
max_reconnect_attempts = 3
health_check_interval_ms = 5000
message_buffer_size = 1000

[executor]
order_timeout_ms = 5000
max_retry_attempts = 2
concurrent_send_count = 2
idempotent_key_prefix = "TEST"

[ipc]
service_name = "trading_engine_test"
input_topic = "test_commands"
output_topic = "test_market_data"
buffer_size = 100

# Test Exchange Configuration
[exchanges.binance]
enabled = false
api_key = "test_api_key"
secret_key = "test_secret_key"

[exchanges.binance.spot]
enabled = false
ws_endpoints = ["wss://stream.binance.com:9443/ws"]
rest_endpoint = "https://api.binance.com"
connection_count = 1

[exchanges.binance.futures]
enabled = false
ws_endpoints = ["wss://fstream.binance.com/ws"]
rest_endpoint = "https://fapi.binance.com"
connection_count = 1